# Copyright (c) 2023 Intel Corporation
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#
# SPDX-License-Identifier: MIT

title: Scene Classification Training
version: 1.0.0
description: Tailor-train a pretrained VGG16_365 model with your custom data that can classify an image’s background scenery
long_description: Tailor-train a pretrained VGG16_365 model (the VGG16 model trained on the Places-365 dataset) with your custom data, and deploy an endpoint, which can classify an image’s background scenery to one of predefined natural scene categories.
author: "cnvrg"
author_email: "libhub@cnvrg.io"

tags:
  - training
tasks:
  - title: S3 Connector
    top: 300
    left: 0

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: s3-connector
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python s3-connector.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg/cnvrg:v5.0
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      - key: endpoint
        type: 'categorical'
        values:
          - 'http://s3.amazonaws.com download'
      - key: bucketname
        type: 'categorical'
        values:
          - 'libhub-readme'
      - key: localdir
        type: 'categorical'
        values:
          - '/cnvrg'
      - key: prefix
        type: 'categorical'
        values:
          - 'scene_detection/'
    
  - title: Train
    top: 300
    left: 250

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: scene-classification-train
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python3 train.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg/cnvrg:v5.0
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      - key: img_dir
        type: 'categorical'
        values:
           - '/input/s3_connector/scene_detection/training_images/'
      - key: epochs
        type: 'categorical'
        values:
           - '50'
      - key: training_args
        type: 'categorical'
        values:
           - '30,0.15,0.2,0.2,0.15'
      - key: dimensions
        type: 'discrete'
        values:
           - '123.68,116.779,103.939'
      - key: target_size
        type: 'discrete'
        values:
           - '224.00,224.00'
      - key: loss
        type: 'categorical'
        values:
           - 'categorical_crossentropy'
      - key: metrics
        type: 'categorical'
        values:
           - 'accuracy'
      - key: lr
        type: 'discrete'
        values:
           - '1e-4'
      - key: momentum
        type: 'discrete'
        values:
           - '0.9'
  - title: Inference
    top: 300
    left: 500

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: deploy

    # The library data
    library: scene-classification-inference
    library_version: 1.0.0

    command: python3 predict.py
    kind: webservice

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg/cnvrg:v5.0
    language: python3
    accept_files: false

    file_name: predict.py # the entrypoint file name
    function_name: predict # the entrypoint function
    prep_file: '' # preprocess file name
    prep_function: '' # preprocess function
    input_example:
      img: file
    input_schema:
      img: file
    output_schema: {}

  - title: Batch-Predict
    top: 400
    left: 500

    # Type must be according to the flow task conventions (data, exec, deploy)
    type: exec

    # The library data
    library: scene-classification-batch
    library_version: 1.0.0

    # The flattened library parameters (in this case we have training library)
    command: python3 batch_predict.py

    requirements:
      cpu: 3.5
      memory: 8
      gpu: 0
      hpu: 0

    image: cnvrg:v5.0
    language: python3

    # The "arguments" property changes to "params", rest remains the same.
    # Params in the blueprint yaml can be used to override the arguments in the library.
    params:
      - key: 'img_dir'
        type: 'categorical'
        values:
          - '/input/s3_connector/scene_detection/test_images/'
      - key: 'model_dir'
        type: 'categorical'
        values:
          - '/input/train/my_model_weights.h5'
      - key: 'using_default'
        type: 'categorical'
        values:
          - 'no'
      - key: 'top_pred'
        type: 'discrete'
        values:
          - '5'
      - key: 'dimensions'
        type: 'discrete'
        values:
          - "123.68,116.779,103.939"
      - key: 'target_size'
        type: 'discrete'
        values:
          - "224.00,224.00"
      - key: 'class_names'
        type: 'categorical'
        values:
          - '/input/train/class_names.csv'
      - key: 'loss'
        type: 'categorical'
        values:
          - 'categorical_crossentropy'
      - key: 'metrics'
        type: 'categorical'
        values:
          - 'accuracy'
      - key: 'lr'
        type: 'discrete'
        values:
          - '1e-4'
      - key: 'momentum'
        type: 'discrete'
        values:
          - '0.9'

relations:
  - from: S3 Connector
    to: Train
  - from: Train
    to: Inference
  - from: Train
    to: Batch-Predict
